function PlotImgHist(cdata1, X1, Y1)
%CREATEFIGURE(CDATA1, X1, Y1)
%  CDATA1:  image cdata
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 10-May-2018 15:56:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.01 0.11 0.5 0.815]);
axis off
hold(axes1,'on');

% Create image
colormap('gray')
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

box(axes1,'on');
axis(axes1,'tight');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'Layer','top','TickDir','out');
% Create axes
axes2 = axes('Parent',figure1,'Position',[0.55 0.25 0.4 0.5]);
hold(axes2,'on');

% Create stem
stem(X1,Y1,'Parent',axes2,'LineWidth',1);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 1]);
box(axes2,'on');
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',22,'YAxisLocation','right');
